# This is a CI workflow for the NCEPLIBS-sigio project.
#
# This workflow builds with the Intel Classic and OneAPI compilers.
#
# Alex Richert, Sep 2023
name: Intel
on:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop

jobs:
  Intel:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compilers: ["CC=icc FC=ifort", "CC=icx FC=ifx"]

    steps:

    - name: "Install Intel"
      uses: NOAA-EMC/ci-install-intel-toolkit@develop

    - name: checkout
      uses: actions/checkout@v2
      with: 
        path: sigio

    - name: build
      run: |
        cd sigio
        mkdir build && cd build
        ${{ matrix.compilers }} cmake .. -DENABLE_TESTS=ON
        make -j2 VERBOSE=1

    - name: test-sigio
      run: |
        cd sigio/build
        ctest --verbose --output-on-failure --rerun-failed
