name: Build and Test
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        gcc-version: [12,14]

    steps:

    - name: get-gcc
      run: |
        if [ -z $(type -P gcc-${{ matrix.gcc-version }}) ]; then
          sudo apt install gcc-${{ matrix.gcc-version }}
        fi

    - name: Installs
      run: sudo apt-get install doxygen graphviz 

    - name: checkout
      uses: actions/checkout@v4
      with: 
        path: sigio

    - name: Build
      uses: AlexanderRichert-NOAA/ci-cache-cmake-build/build-code@main
      with:
        parent-org: AlexanderRichert-NOAA
        source-dir: sigio
        build-dir: build/
    
    - name: test
      run: ctest --test-dir build --output-on-failure

