name: Build and Test
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        gcc-version: [12,14]

    steps:

    - name: get-gcc
      run: |
        if [ -z $(type -P gcc-${{ matrix.gcc-version }}) ]; then
          sudo apt install gcc-${{ matrix.gcc-version }}
        fi

    - name: Installs
      run: sudo apt-get install doxygen graphviz 

    - name: checkout
      uses: actions/checkout@v4
      with: 
        path: sigio

    - name: build
      run: |
        export CC=gcc-${{ matrix.gcc-version }} ; export FC=gfortran-${{ matrix.gcc-version }}
        cmake -S sigio -B sigio/build -DENABLE_DOCS=ON
        cmake --build sigio/build --parallel 2 --verbose
    
    - name: test
      run: ctest --test-dir sigio/build --output-on-failure
