name: Build and Test
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FC: gfortran-11
      CC: gcc-11

    steps:

    - name: Installs
      run: sudo apt-get install doxygen graphviz 

    - name: checkout
      uses: actions/checkout@v4
      with: 
        path: sigio

    - name: build
      run: |
        cmake -S sigio -B sigio/build -DENABLE_DOCS=ON
        cmake sigio/build --parallel 2 --verbose
    
    - name: test
      run: ctest --test-dir sigio/build --output-on-failure
