name: Build and Test
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FC: gfortran-11
      CC: gcc-11

    steps:

    - name: Installs
      run: |
        sudo apt-get install doxygen graphviz 

    - name: checkout
      uses: actions/checkout@v2
      with: 
        path: sigio

    - name: build
      run: |
        cd sigio
        mkdir build 
        cd build
        cmake -DENABLE_TESTS=ON -DENABLE_DOCS=ON ..
        make -j2
    
    - name: test
      run: |
        cd $GITHUB_WORKSPACE/sigio/build
        make test
